[package]
authors = ["iRennegade"]
edition = "2021"
name = "petas-net"
version = "0.1.0"

[[bin]]
name = "petas"
path = "src/main.rs"

[dependencies]
rand = "0.8.5"
regex = "1"
reqwest = {version = "0.11.13", features = ["blocking"]}
